---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/epic-internal-gateway: "true"
    kubedirector.bluedata.io/epic-internal-gateway: "true"
  name: hello-world-app
spec:
  selector:
    app: hello-world-app
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: NodePort
